{% set name = "ribometric" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/RiboMetric-{{ version }}.tar.gz
  sha256: 4eeabcac739c7054a2f7c3cb4a64b1a0537b65b829923279d70729d0cf03ee5d

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - arabic_reshaper ==3.0.0
    - asn1crypto ==1.5.1
    - bio ==1.5.9
    - biopython ==1.81
    - biothings_client ==0.3.0
    - certifi ==2022.12.7
    - cffi ==1.15.1
    - charset-normalizer ==3.1.0
    - click ==8.1.3
    - cryptography ==40.0.2
    - cssselect2 ==0.7.0
    - cython ==0.29.34
    - gffpandas ==1.2.0
    - gprofiler-official ==1.0.0
    - html5lib ==1.1
    - idna ==3.4
    - jinja2 ==3.1.2
    - python-kaleido ==0.2.1
    - lxml ==4.9.2
    - markdown-it-py ==2.2.0
    - markupsafe ==2.1.2
    - mdurl ==0.1.2
    - mygene ==3.2.2
    - numpy ==1.24.3
    - oscrypto ==1.3.0
    - oxbow ==0.1.0
    - packaging ==23.1
    - pandas ==2.0.1
    - pillow ==9.5.0
    - platformdirs ==3.4.0
    - plotly ==5.14.1
    - pooch ==1.7.0
    - pyarrow ==12.0.0
    - pycparser ==2.21
    - pygments ==2.15.1
    - pyhanko ==0.18.1
    - pyhanko-certvalidator ==0.22.0
    - pypdf ==3.9.0
    - pypng ==0.20220715.0
    - pysam ==0.21.0
    - pytest ==7.3.1
    - python-bidi ==0.4.2
    - python-dateutil ==2.8.2
    - pytz ==2023.3
    - pyyaml ==6.0
    - qrcode ==7.4.2
    - reportlab ==3.6.13
    - requests ==2.29.0
    - rich ==13.3.4
    - six ==1.16.0
    - svglib ==1.5.1
    - tenacity ==8.2.2
    - tinycss2 ==1.2.1
    - tqdm ==4.65.0
    - typing-extensions ==4.5.0
    - tzdata ==2023.3
    - tzlocal ==5.0.1
    - uritools ==4.0.1
    - urllib3 ==1.26.15
    - webencodings ==0.5.1
    - xhtml2pdf ==0.2.11

test:
  imports:
    - ribometric
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JackCurragh/RiboMetric
  summary: A python command-line utility for the generation of comprehensive reports on the quality of ribosome profiling (Ribo-Seq) datasets
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JackCurragh
