plots:
  font_family: Helvetica Neue,Helvetica,Arial,sans-serif
  base_color: '#7f7f7f'
  nucleotide_colors: {"A": "#c93434", "C": "#2e85db", "G": "#f0de1f", "T": "#1fc24d"}
  read_frame_distribution:
    upper_limit: 40
    lower_limit: 10
  ligation_bias_distribution:
    include_N: True