plots:
  # Controls general plot theming and specific plot options
  font_family: Helvetica Neue,Helvetica,Arial,sans-serif
  base_color: '#7f7f7f'
  nucleotide_colors: {"A": "#c93434", "C": "#2e85db", "G": "#f0de1f", "T": "#1fc24d"}
  image_size: [720, 360]      # [Width, Height] in pixels, used for pdf images
  ligation_bias_distribution:
    nucleotide_count: 2
    include_N: False
  nucleotide_proportion:
    nucleotide_start: 0
    nucleotide_count: 15
  read_frame_distribution:
    upper_limit: 40
    lower_limit: 15
    show_scores: "all"        # Options: ["all", "global", "none"]
  mRNA_distribution:
    upper_limit: 50
    lower_limit: 10
    absolute_counts: False    # Options for both?
  mRNA_read_breakdown:
    upper_limit: 50
    lower_limit: 10
    absolute_counts: False
  metagene_profile:
    distance_target: "start"  # Options: ["start", "stop"] # Add both? grid plot
    distance_range: [-30,30]
    colorscale: "electric"    # Heatmap colorscale, see https://plotly.com/python/builtin-colorscales/
    max_colorscale: 350       # set to 'None' (without quotes!) for automatic maximum
qc:
  use_cds_subset:
  # Defines which modules use only reads that are on cds
  # If False, uses all reads
    read_frame_distribution: False