plots:
  # Controls general plot theming and specific plot options
  font_family: Helvetica Neue,Helvetica,Arial,sans-serif
  base_color: '#7f7f7f'
  nucleotide_colors: {"A": "#c93434", "C": "#2e85db", "G": "#f0de1f", "T": "#1fc24d"}
  ligation_bias_distribution:
    include_N: True
  read_frame_distribution:
    upper_limit: 40
    lower_limit: 15
    show_scores: "all" #Options: ["all", "global", "none"]
  mRNA_distribution:
    upper_limit: 50
    lower_limit: 10
    absolute_counts: False
  mRNA_read_breakdown:
    upper_limit: 50
    lower_limit: 10
    absolute_counts: False
  metagene_profile:
    distance_target: "start" #Options: ["start", "stop"]
    distance_range: [-100,100]
qc:
  use_cds_subset:
  # Defines which modules use only reads that are on cds
  # If False, uses all reads
    read_frame_distribution: False