#!/usr/bin/env python
#
# RiboMetric documentation build configuration file, created by
# sphinx-quickstart on Fri Jun  9 13:47:02 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another
# directory, add these directories to sys.path here. If the directory is
# relative to the documentation root, use os.path.abspath to make it
# absolute, like shown here.
#
import RiboMetric


import os
import sys

sys.path.insert(0, os.path.abspath(".."))


# -- General configuration ---------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
# myst_parser lets the Markdown docs (METRICS.md, METRICS_DESIGN.md,
# REPORTING_GUIDE.md, RELEASE.md) go in the toctree. Without it
# source_suffix is .rst only and they are unreachable on the site.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.viewcode",
    "sphinx.ext.napoleon",
    "myst_parser",
]

# The codebase documents parameters as "Inputs:" / "Outputs:" with an indented
# block. That is not valid RST -- docutils read the indent as a block quote and
# emitted ~35 "Unexpected indentation" errors across the API reference. Rather
# than rewrite every docstring, teach napoleon the two section names the
# project actually uses, so they render as proper parameter and return fields.
# Both the plural and singular spellings are in use: "Inputs:"/"Outputs:" in
# metrics.py and modules.py, "Input:"/"Output:" throughout results_output.py
# and plots.py. Registering all four means 155 docstrings render as proper
# parameter and return fields instead of as an undifferentiated paragraph.
napoleon_custom_sections = [
    ("Inputs", "params_style"),
    ("Outputs", "returns_style"),
    ("Input", "params_style"),
    ("Output", "returns_style"),
]

# Do not pull docstrings down from base classes. RiboMetric's TUI subclasses
# textual, whose docstrings are MkDocs-flavoured Markdown -- fenced code
# blocks, `backtick` spans and [label][target] cross-references, none of which
# is valid reStructuredText. HelpScreen.compose has no docstring of its own, so
# autodoc was inheriting textual's and emitting six warnings from a third
# party's prose that no change here could fix.
autodoc_inherit_docstrings = False

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = {".rst": "restructuredtext", ".md": "markdown"}

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "RiboMetric"
copyright = "2023, Jack Tierney"
author = "Jack Tierney"

# The version info for the project you're documenting, acts as replacement
# for |version| and |release|, also used in various other places throughout
# the built documents.
#
# The short X.Y version.
version = RiboMetric.__version__
# The full version, including alpha/beta/rc tags.
release = RiboMetric.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
# Internal working notes, not user documentation. They live in docs/ for
# convenience but are deliberately not published.
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "AUDIT_NOTES.md",
    "SCORING_PHASE1_TASKS.md",
    "TESTING.md",
    "V1.2_REPORT_AND_PREPRINT_PLAN.md",
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output -------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "alabaster"

# Theme options are theme-specific and customize the look and feel of a
# theme further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# No _static assets are shipped; pointing at a missing directory warns.
html_static_path = []


# -- Options for HTMLHelp output ---------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "RiboMetricdoc"


# -- Options for LaTeX output ------------------------------------------

from typing import Dict, Any

latex_elements: Dict[str, Any] = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass
# [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "RiboMetric.tex",
        "RiboMetric Documentation",
        "Jack Tierney",
        "manual",
    ),
]


# -- Options for manual page output ------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, "RiboMetric", "RiboMetric Documentation", [author], 1)
]


# -- Options for Texinfo output ----------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "RiboMetric",
        "RiboMetric Documentation",
        author,
        "RiboMetric",
        "One line description of project.",
        "Miscellaneous",
    ),
]


# `modules` in index.rst is produced by sphinx-apidoc. `make docs` runs that
# locally, but Read the Docs only runs sphinx-build -- so without this hook the
# toctree entry dangles and the API reference is missing from the published
# site. Generating it here means one code path for both.
def run_apidoc(_):
    from sphinx.ext.apidoc import main as apidoc_main

    here = os.path.dirname(__file__)
    apidoc_main(["-o", here, "-f", os.path.join(here, "..", "RiboMetric")])


def setup(app):
    app.connect("builder-inited", run_apidoc)
